### PR TITLE
upgrading airflow from 2.1.1 to 2.2.5

### PR DESCRIPTION
**Pull request by jeanlegrais**
In order to upgrade the framwork to airflow 2.2.5 :
- PythonOperator changed its source : airflow.operators.python
- BigQueryHook changed its source and some params : airflow.providers.google.cloud.hooks.bigquery | gcp_conn_id
- GoogleCloudStorageHook becomes GCSHook with new params : gcp_conn_id
- BaseHook changed its source : airflow.hooks.base
- apply_defaults is not a decorator anymore : need to declare them in a dag
- BigQueryHook doesnt need cursor anymore and in some cases you can use : BigQueryCursor
- BigQueryOperator is replaced by some classes such as BigQueryExecuteQueryOperator used here for sql

Some tests were commented :
- rmv test_dlp,TestCustomBigQueryCreateEmptyTableOperator,  and test_gcs

### CODE REVIEW

**Comment by eugenemiretsky** [comment]
@jeanlegrais 
Can we please create JIRAs to 
1) Fix the unit tests you removed
2) Upgrade to latest Airflow (2.3.5?) - we probably don't need to do it until Compose supports it. But would be good to have a place with some notes of what you have learned now

**Review by jinysong — APPROVED** [review]

**Comment by eugenemiretsky** [comment]
Let's the docker compose locally - we change airflow version, need to upgrade the version in Docker Compose too

**Comment by eugenemiretsky** [comment]
lets bump the Airflow Foundation Version to 0.3.0

**Review by danielkulikov — APPROVED** [review]
Looks good - have we tested the sources this PR changed? e.g. the sftp source

**Comment by jeanlegrais** [comment]
> Looks good - have we tested the sources this PR changed? e.g. the sftp source

@eugenemiretsky

**Comment by eugenemiretsky** [comment]
@danielkulikov @jeanlegrais it is hard to test every single source since we don't have integration tests/ test data. 

We may have to bit the bullet and test when we upgrade the framework version at the specific deployments

**Review by eugenemiretsky — APPROVED** [review]

**Pull request merged**
